sources: 
  - PlaypenSans.glyphspackage
axisOrder:
  - wght
familyName: Playpen Sans
buildVariable: true
buildOTF: false
buildTTF: false
buildWebfont: false
outputDir: "../fonts"
filenameSuffix: Multi
postCompile:
  - operation: rename
    args: --just-family
    name: Playpen Sans Multi
  - operation: exec
    exe: gftools-update-nameids
    args: '-v=1.007 -d="Laura Meseguer, Veronika Burian, José Scaglione, Kostas Bartsokas, Vera Evstafieva, Tom Grace, Yorlmar Campos, Azza Alameddine, Pooja Saxena, Gunjan Panchal, Sirin Gunkloy" $in && mv $in.fix $out'