sources: 
  - PlaypenSans.glyphspackage
axisOrder:
  - wght
familyName: Playpen Sans
buildVariable: true
buildOTF: false
# buildTTF: false
buildWebfont: false
outputDir: "../fonts"
filenameSuffix: Hebrew
postCompile:
  - operation: rename
    args: --just-family
    name: Playpen Sans Hebrew
  - operation: exec
    exe: gftools-update-nameids
    args: '-d="Laura Meseguer, Veronika Burian, José Scaglione, Tom Grace" $in && mv $in.fix $out'
  - operation: exec
    exe: pyftsubset
    args: '$in --output-file=$out --layout-features="*" --notdef-glyph --notdef-outline --name-IDs=* --passthrough-tables --unicodes-file=./helpers/PPS-HEB.nam'
  - operation: exec
    exe: gftools-fontsetter
    args: '$in ./helpers/HEB.yaml -o $out'
