sources: 
  - PlaypenSans.glyphspackage
axisOrder:
  - wght
familyName: Playpen Sans
buildVariable: true
buildOTF: false
buildTTF: false
buildWebfont: false
outputDir: "../fonts-builder-2"
filenameSuffix: Arabic
postCompile:
  - operation: rename
    args: --just-family
    name: Playpen Sans Arabic
  - operation: exec
    exe: pyftsubset
    args: '$in --output-file=$out --layout-features="*" --notdef-glyph --notdef-outline --name-IDs=* --unicodes-file=./helpers/PPS-ARAB.nam'
  - operation: exec
    exe: gftools-fontsetter
    args: '$in ./helpers/ARAB.yaml -o $out'