sources: 
  - PlaypenSans.glyphspackage
axisOrder:
  - wght
familyName: Playpen Sans
buildVariable: true
buildOTF: false
buildTTF: false
buildWebfont: false
outputDir: "../fonts-builder-2"
filenameSuffix: MS
postCompile:
  - operation: rename
    args: --just-family
    name: Playpen Sans MS