sources: 
  - PlaypenSans.glyphspackage
axisOrder:
  - wght
familyName: PlaypenSans
buildVariable: true
buildOTF: false
buildTTF: false
buildWebfont: false
flattenComponents: false
version: 1.004
outputDir: "../fonts-builder"
# stat:
#   PlaypenSans[wght].ttf:
#   - name: Weight
#     tag: wght
#     values:
#     - name: Thin
#       value: 100
#     - name: ExtraLight
#       value: 200
#     - name: Light
#       value: 300
#     - name: Regular
#       value: 400
#       linkedValue: 700
#       flags: 2
#     - name: Medium
#       value: 500
#     - name: SemiBold
#       value: 600
#     - name: Bold
#       value: 700
#     - name: ExtraBold
#       value: 800
# sources:
# - PlaypenSans.glyphspackage
# doGuidelines: false
# buildStatic: true
buildColorVariable: false
recipeProvider: fontprimer
variants:
  - name: LGC
    steps:
      - operation: exec
        exe: pyftsubset
        args: '$in --output-file=$out --layout-features="*" --notdef-glyph --notdef-outline --name-IDs=* --unicodes-file=PPS-LGC.nam'
      - operation: exec
        exe: gftools-fontsetter
        args: '$in LGC.yaml -o $out'
  - name: ARAB
    steps:
      - operation: exec
        exe: pyftsubset
        args: '$in --output-file=$out --layout-features="*" --notdef-glyph --notdef-outline --name-IDs=* --unicodes-file=PPS-ARAB.nam'
      - operation: exec
        exe: gftools-fontsetter
        args: '$in ARAB.yaml -o $out'





